name: Setup CI Environment
description: "Checkout code, set up uv, install Python, and install dependencies"
inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.11"
  sync-group:
    description: "Optional dependency sync group (e.g. 'docs')"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        if [ -z "${{ inputs.sync-group }}" ]; then
          uv sync
        else
          uv sync --group ${{ inputs.sync-group }}
        fi
