name: Publish on PyPI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'docs/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CI Environment for Testing
        uses: ./.github/actions/setup-ci
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CI Environment for Publishing
        uses: ./.github/actions/setup-ci
        with:
          python-version: "3.11"

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --token $PYPI_API_TOKEN
